sudo: required
services:
    - docker

before_install:
    - docker build -t tetherdev/lstry-test -f ./client/Dockerfile.dev ./client

script:
  - docker run tetherdev/lstry-test npm test -- --coverage

after_success:
  - docker build -t tetherdev/lstry-client ./client
  - docker build -t tetherdev/lstry-nginx ./nginx
  - docker build -t tetherdev/lstry-server ./server
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push tetherdev/lstry-client
  - docker push tetherdev/lstry-nginx
  - docker push tetherdev/lstry-server

deploy:
    provider: elasticbeanstalk
    region: us-west-2
    app: lstry
    env: Lstry-env
    bucket_name: elasticbeanstalk-us-west-2-075083687404
    bucket_path: lstry
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key:
        secure: $AWS_SECRET_KEY