sudo: required
services:
    - docker

before_install:
    - docker build -t tetherdev/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run tetherdev/react-test npm test -- --coverage

after_success:
  - docker build -t tetherdev/multi-client ./client
  - docker build -t tetherdev/multi-nginx ./nginx
  - docker build -t tetherdev/multi-server ./server
  - docker build -t tetherdev/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push tetherdev/multi-client
  - docker push tetherdev/multi-nginx
  - docker push tetherdev/multi-server
  - docker push tetherdev/multi-worker

deploy:
    provider: elasticbeanstalk
    region: us-west-2
    app: multi-docker
    env: MultiDocker-env
    bucket_name: elasticbeanstalk-us-west-2-075083687404
    bucket_path: docker_multi
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key:
        secure: $AWS_SECRET_KEY