sudo: required
services:
    - docker

before_install:
    - docker build -t tetherdev/react-test -f .client/Docerfile.dev ./client

script:
  - docker run tetherdev/react-test npm test -- --coverage

after_success:
  - docker build -t tetherdev/multi-client ./client
  - docker build -t tetherdev/multi-nginx ./nginx
  - docker build -t tetherdev/multi-server ./server
  - docker build -t tetherdev/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push tetherdev/multi-client
  - docker push tetherdev/multi-nginx
  - docker push tetherdev/multi-server
  - docker push tetherdev/multi-worker