version: '3'
services: 
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - '3050:80'
  api:
    build:
      dockerfile: Dockerfile.dev
      context: ./server
    volumes:
      - /app/node_modules
      - ./server:/app
    environment:
      - NODE_ENV=development
      - PORT=5000
      - MONGOLAB_URI=mongodb://interface_connect:1Tkr5bn87YwlhBt0@ds151289.mlab.com:51289/proofbot
      - CLIENT_ID=4027298504.412391786784
      - CLIENT_SECRET=feed9a301ee940410a9846ed7dec50d4
      - CALLBACK_URI=http://localhost:3050/auth/slack/callback
      - SESSION_SECRET=9T8a6RKwZbmRmODX
  client:
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app


